name: LunarSandBotRecoded
version: ${project.version}
main: me.magas8.LunarSandBot
depend: [Vault]
softdepend: [Factions,FactionsX,FactionsUUID,MassiveCore]
commands:
  sandbot:
    description: Shows help menu of this plugin
    usage: /sandbot

